package com.example.TestAPI.Model.Enum;

public enum ActionType {
    REGISTER,
    LOGIN,
    LOGOUT,
    CREATE_JOB,
    UPDATE_JOB,
    DELETE_JOB,
    ASSIGN_JOB,
    COMPLETE_JOB,
    UPDATE_PROFILE,
    KYC_SUBMITTED,
    KYC_APPROVED,
    KYC_REJECTED,
    START_CONVERSATION,
    SEND_MESSAGE,
    PAYMENT_INITIATED,
    PAYMENT_CONFIRMED,
    SUBMIT_RATING,
    PASSWORD_RESET,
    EXPIRE_JOB
}